stages:
    - deploy

deploy-server:
  stage: deploy
  environment:
    name: development
    url: https://rudabi.kemenag.dev/
  script:
    - sshpass -p ${SSH_PWD} ssh -oStrictHostKeyChecking=no -p ${SSH_PORT} ${SSH_LOGIN} -t "cd /var/www/html/Rudabi && sh update.sh"
    - echo "Job-mu is sukespulll!"
  only:
    - main
