
-- --------------------------------------------------------

--
-- Table structure for table `mt_country`
--

DROP TABLE IF EXISTS `mt_country`;
CREATE TABLE `mt_country` (
  `id` int NOT NULL,
  `code` varchar(2) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `country` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `flags` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci DEFAULT NULL,
  `stat` int DEFAULT NULL,
  `syscreateuser` int DEFAULT NULL,
  `syscreatedate` datetime DEFAULT NULL,
  `sysupdateuser` int DEFAULT NULL,
  `sysupdatedate` datetime DEFAULT NULL,
  `sysdeleteuser` int DEFAULT NULL,
  `sysdeletedate` datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `mt_country`
--

INSERT INTO `mt_country` (`id`, `code`, `country`, `flags`, `stat`, `syscreateuser`, `syscreatedate`, `sysupdateuser`, `sysupdatedate`, `sysdeleteuser`, `sysdeletedate`) VALUES
(1, 'AD', 'Andorra', 'AD.png', 1, NULL, NULL, 1, '2021-03-16 03:39:07', NULL, NULL),
(2, 'AE', 'United Arab Emirates', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(3, 'AF', 'Afghanistan', 'AF.png', 1, NULL, NULL, 1, '2021-03-16 03:33:01', NULL, NULL),
(4, 'AG', 'Antigua and Barbuda', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(5, 'AI', 'Anguilla', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(6, 'AL', 'Albania', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(7, 'AM', 'Armenia', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(8, 'AO', 'Angola', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(9, 'AQ', 'Antarctica', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(10, 'AR', 'Argentina', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(11, 'AS', 'American Samoa', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(12, 'AT', 'Austria', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(13, 'AU', 'Australia', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(14, 'AW', 'Aruba', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(15, 'AX', 'Åland Islands', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(16, 'AZ', 'Azerbaijan', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(17, 'BA', 'Bosnia and Herzegovina', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(18, 'BB', 'Barbados', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(19, 'BD', 'Bangladesh', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(20, 'BE', 'Belgium', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(21, 'BF', 'Burkina Faso', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(22, 'BG', 'Bulgaria', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(23, 'BH', 'Bahrain', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(24, 'BI', 'Burundi', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(25, 'BJ', 'Benin', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(26, 'BL', 'Saint Barthélemy', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(27, 'BM', 'Bermuda', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(28, 'BN', 'Brunei Darussalam', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(29, 'BO', 'Bolivia, Plurinational State of', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(30, 'BQ', 'Bonaire, Sint Eustatius and Saba', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(31, 'BR', 'Brazil', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(32, 'BS', 'Bahamas', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(33, 'BT', 'Bhutan', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(34, 'BV', 'Bouvet Island', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(35, 'BW', 'Botswana', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(36, 'BY', 'Belarus', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(37, 'BZ', 'Belize', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(38, 'CA', 'Canada', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(39, 'CC', 'Cocos (Keeling) Islands', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(40, 'CD', 'Congo, the Democratic Republic of the', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(41, 'CF', 'Central African Republic', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(42, 'CG', 'Congo', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(43, 'CH', 'Switzerland', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(44, 'CI', 'Côte d\'Ivoire', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(45, 'CK', 'Cook Islands', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(46, 'CL', 'Chile', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(47, 'CM', 'Cameroon', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(48, 'CN', 'China', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(49, 'CO', 'Colombia', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(50, 'CR', 'Costa Rica', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(51, 'CU', 'Cuba', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(52, 'CV', 'Cape Verde', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(53, 'CW', 'Curaçao', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(54, 'CX', 'Christmas Island', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(55, 'CY', 'Cyprus', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(56, 'CZ', 'Czech Republic', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(57, 'DE', 'Germany', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(58, 'DJ', 'Djibouti', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(59, 'DK', 'Denmark', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(60, 'DM', 'Dominica', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(61, 'DO', 'Dominican Republic', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(62, 'DZ', 'Algeria', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(63, 'EC', 'Ecuador', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(64, 'EE', 'Estonia', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(65, 'EG', 'Egypt', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(66, 'EH', 'Western Sahara', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(67, 'ER', 'Eritrea', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(68, 'ES', 'Spain', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(69, 'ET', 'Ethiopia', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(70, 'FI', 'Finland', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(71, 'FJ', 'Fiji', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(72, 'FK', 'Falkland Islands (Malvinas)', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(73, 'FM', 'Micronesia, Federated States of', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(74, 'FO', 'Faroe Islands', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(75, 'FR', 'France', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(76, 'GA', 'Gabon', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(77, 'GB', 'United Kingdom', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(78, 'GD', 'Grenada', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(79, 'GE', 'Georgia', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(80, 'GF', 'French Guiana', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(81, 'GG', 'Guernsey', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(82, 'GH', 'Ghana', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(83, 'GI', 'Gibraltar', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(84, 'GL', 'Greenland', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(85, 'GM', 'Gambia', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(86, 'GN', 'Guinea', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(87, 'GP', 'Guadeloupe', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(88, 'GQ', 'Equatorial Guinea', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(89, 'GR', 'Greece', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(90, 'GS', 'South Georgia and the South Sandwich Islands', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(91, 'GT', 'Guatemala', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(92, 'GU', 'Guam', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(93, 'GW', 'Guinea-Bissau', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(94, 'GY', 'Guyana', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(95, 'HK', 'Hong Kong', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(96, 'HM', 'Heard Island and McDonald Islands', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(97, 'HN', 'Honduras', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(98, 'HR', 'Croatia', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(99, 'HT', 'Haiti', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(100, 'HU', 'Hungary', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(101, 'ID', 'Indonesia', 'id.png', 1, NULL, NULL, NULL, NULL, NULL, NULL),
(102, 'IE', 'Ireland', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(103, 'IL', 'Israel', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(104, 'IM', 'Isle of Man', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(105, 'IN', 'India', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(106, 'IO', 'British Indian Ocean Territory', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(107, 'IQ', 'Iraq', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(108, 'IR', 'Iran, Islamic Republic of', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(109, 'IS', 'Iceland', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(110, 'IT', 'Italy', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(111, 'JE', 'Jersey', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(112, 'JM', 'Jamaica', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(113, 'JO', 'Jordan', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(114, 'JP', 'Japan', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(115, 'KE', 'Kenya', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(116, 'KG', 'Kyrgyzstan', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(117, 'KH', 'Cambodia', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(118, 'KI', 'Kiribati', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(119, 'KM', 'Comoros', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(120, 'KN', 'Saint Kitts and Nevis', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(121, 'KP', 'Korea, Democratic People\'s Republic of', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(122, 'KR', 'Korea, Republic of', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(123, 'KW', 'Kuwait', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(124, 'KY', 'Cayman Islands', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(125, 'KZ', 'Kazakhstan', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(126, 'LA', 'Lao People\'s Democratic Republic', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(127, 'LB', 'Lebanon', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(128, 'LC', 'Saint Lucia', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(129, 'LI', 'Liechtenstein', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(130, 'LK', 'Sri Lanka', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(131, 'LR', 'Liberia', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(132, 'LS', 'Lesotho', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(133, 'LT', 'Lithuania', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(134, 'LU', 'Luxembourg', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(135, 'LV', 'Latvia', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(136, 'LY', 'Libya', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(137, 'MA', 'Morocco', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(138, 'MC', 'Monaco', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(139, 'MD', 'Moldova, Republic of', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(140, 'ME', 'Montenegro', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(141, 'MF', 'Saint Martin (French part)', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(142, 'MG', 'Madagascar', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(143, 'MH', 'Marshall Islands', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(144, 'MK', 'Macedonia, the Former Yugoslav Republic of', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(145, 'ML', 'Mali', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(146, 'MM', 'Myanmar', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(147, 'MN', 'Mongolia', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(148, 'MO', 'Macao', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(149, 'MP', 'Northern Mariana Islands', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(150, 'MQ', 'Martinique', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(151, 'MR', 'Mauritania', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(152, 'MS', 'Montserrat', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(153, 'MT', 'Malta', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(154, 'MU', 'Mauritius', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(155, 'MV', 'Maldives', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(156, 'MW', 'Malawi', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(157, 'MX', 'Mexico', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(158, 'MY', 'Malaysia', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(159, 'MZ', 'Mozambique', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(160, 'NA', 'Namibia', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(161, 'NC', 'New Caledonia', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(162, 'NE', 'Niger', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(163, 'NF', 'Norfolk Island', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(164, 'NG', 'Nigeria', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(165, 'NI', 'Nicaragua', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(166, 'NL', 'Netherlands', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(167, 'NO', 'Norway', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(168, 'NP', 'Nepal', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(169, 'NR', 'Nauru', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(170, 'NU', 'Niue', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(171, 'NZ', 'New Zealand', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(172, 'OM', 'Oman', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(173, 'PA', 'Panama', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(174, 'PE', 'Peru', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(175, 'PF', 'French Polynesia', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(176, 'PG', 'Papua New Guinea', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(177, 'PH', 'Philippines', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(178, 'PK', 'Pakistan', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(179, 'PL', 'Poland', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(180, 'PM', 'Saint Pierre and Miquelon', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(181, 'PN', 'Pitcairn', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(182, 'PR', 'Puerto Rico', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(183, 'PS', 'Palestine, State of', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(184, 'PT', 'Portugal', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(185, 'PW', 'Palau', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(186, 'PY', 'Paraguay', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(187, 'QA', 'Qatar', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(188, 'RE', 'Réunion', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(189, 'RO', 'Romania', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(190, 'RS', 'Serbia', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(191, 'RU', 'Russian Federation', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(192, 'RW', 'Rwanda', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(193, 'SA', 'Saudi Arabia', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(194, 'SB', 'Solomon Islands', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(195, 'SC', 'Seychelles', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(196, 'SD', 'Sudan', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(197, 'SE', 'Sweden', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(198, 'SG', 'Singapore', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(199, 'SH', 'Saint Helena, Ascension and Tristan da Cunha', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(200, 'SI', 'Slovenia', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(201, 'SJ', 'Svalbard and Jan Mayen', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(202, 'SK', 'Slovakia', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(203, 'SL', 'Sierra Leone', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(204, 'SM', 'San Marino', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(205, 'SN', 'Senegal', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(206, 'SO', 'Somalia', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(207, 'SR', 'Suriname', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(208, 'SS', 'South Sudan', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(209, 'ST', 'Sao Tome and Principe', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(210, 'SV', 'El Salvador', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(211, 'SX', 'Sint Maarten (Dutch part)', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(212, 'SY', 'Syrian Arab Republic', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(213, 'SZ', 'Swaziland', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(214, 'TC', 'Turks and Caicos Islands', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(215, 'TD', 'Chad', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(216, 'TF', 'French Southern Territories', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(217, 'TG', 'Togo', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(218, 'TH', 'Thailand', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(219, 'TJ', 'Tajikistan', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(220, 'TK', 'Tokelau', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(221, 'TL', 'Timor-Leste', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(222, 'TM', 'Turkmenistan', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(223, 'TN', 'Tunisia', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(224, 'TO', 'Tonga', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(225, 'TR', 'Turkey', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(226, 'TT', 'Trinidad and Tobago', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(227, 'TV', 'Tuvalu', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(228, 'TW', 'Taiwan, Province of China', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(229, 'TZ', 'Tanzania, United Republic of', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(230, 'UA', 'Ukraine', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(231, 'UG', 'Uganda', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(232, 'UM', 'United States Minor Outlying Islands', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(233, 'US', 'United States', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(234, 'UY', 'Uruguay', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(235, 'UZ', 'Uzbekistan', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(236, 'VA', 'Holy See (Vatican City State)', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(237, 'VC', 'Saint Vincent and the Grenadines', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(238, 'VE', 'Venezuela, Bolivarian Republic of', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(239, 'VG', 'Virgin Islands, British', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(240, 'VI', 'Virgin Islands, U.S.', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(241, 'VN', 'Viet Nam', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(242, 'VU', 'Vanuatu', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(243, 'WF', 'Wallis and Futuna', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(244, 'WS', 'Samoa', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(245, 'YE', 'Yemen', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(246, 'YT', 'Mayotte', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(247, 'ZA', 'South Africa', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(248, 'ZM', 'Zambia', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL),
(249, 'ZW', 'Zimbabwe', NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL);
